# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Date
version:      1.03
version_from: lib/Email/Date.pm
installdirs:  site
requires:
    Date::Parse:                   2.27
    Email::Simple:                 1.9
    Test::More:                    0.47
    Time::Local:                   1.07
    Time::Piece:                   1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
